export const PACKAGES = [
  'core',
  'core/http',
  'core/rxjs',
  'cdk',
  'cdk/layout',
  'cdk/dialog',
  'cdk/portal',
  '!forms',
  'router',
  'icons',
  'elements',
  'theming',
  'theming-material',
  '!command-flow',
  '!command-flow/process-flow',
  '!command-flow/query-flow',
  '!command-flow/effects',
  '!command-flow/debugger',
  'endpoints',
  'config-files',
  '!fire',
  'ngx-view-transition',
] as const;

export type Package = (typeof PACKAGES)[number];
